<?php

/**
 * @file
 * Contains dxpr_builder_parse_test.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function dxpr_builder_parse_test_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.parse_html_test':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Test module for DXPR Builder HTML parsing functionality.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function dxpr_builder_parse_test_theme($existing, $type, $theme, $path) {
  return [
    'parse_html_test' => [
      'variables' => [
        'node' => NULL,
        'node_render' => NULL,
        'examples' => NULL,
      ],
      'template' => 'parse-html-test',
    ],
  ];
}

/**
 * Implements template_preprocess_HOOK().
 */
function template_preprocess_parse_html_test(&$variables) {
  $variables['#attached']['library'][] = 'dxpr_builder_parse_test/parse-html-test';
} 