<?php

function dxpr_qa_demo_install() {
  // override existing configuration objects
  $cfg = \Drupal::configFactory()->getEditable('dxpr_qa_demo.dxpr_theme.settings');
  $settings = \Drupal::configFactory()->getEditable('dxpr_theme.settings');
  $settings->setData($cfg->get())->save();
  $cfg->delete();

  $cfg = \Drupal::configFactory()->getEditable('dxpr_qa_demo.dxpr_builder.settings');
  $settings = \Drupal::configFactory()->getEditable('dxpr_builder.settings');
  $settings->setData($cfg->get())->save();
  $cfg->delete();

  $cfg = \Drupal::configFactory()->getEditable('dxpr_qa_demo.workflows.workflow.editorial');
  $settings = \Drupal::configFactory()->getEditable('workflows.workflow.editorial');
  $settings->setData($cfg->get())->save();
  $cfg->delete();

  // generate themesettings css
  $theme_path = \Drupal::service('extension.list.theme')->getPath('dxpr_theme');
  require_once($theme_path . '/dxpr_theme_callbacks.inc');
  dxpr_theme_css_cache_build('dxpr_theme');
}
